/* AUTO-GENERATED by scripts/analyze/_tmp_probe.py —— 离线校验用，不进固件、不进 Keil 工程。
 * 下面的 TURN 宏 / kTurnTbl / 函数体**逐字抽取自 Navigation/map.c**（脚本里有可逆的保真性断言）。
 * 编译：arm-none-eabi-gcc -std=c99 -Wall -Wextra -O0 -c _probe_gen.c
 * 说明：只做语法与保真性校验，不在 PC 上执行（本机无主机编译器 / 无 qemu / 无 gdb-sim）。 */
#include <math.h>
typedef unsigned char u8;
typedef unsigned short u16;
typedef unsigned int u32;

enum { ARRIVE_NONE=0, ARRIVE_DLEFT, ARRIVE_DRIGHT, ARRIVE_CLEFT, ARRIVE_MCLEFT,
       ARRIVE_MCRIGHT, ARRIVE_CRIGHT, ARRIVE_MORELED, ARRIVE_AWHITE,
       ARRIVE_MUL2SING, ARRIVE_MUL2MUL };
#define NONE 1
#define DOOR 13
typedef struct _node { u8 nodenum; u32 flag; float angle; u16 step; float speed; u8 function; } NODE;

/* ===== 节点编号（按 map.h 的 enum MapNode 真实规则）===== */
#define S1     0
#define P1     1
#define N1     2
#define B1     3
#define B2     4
#define B3     5
#define N2     6
#define P2     7
#define S2     8
#define P3     9
#define N3     10
#define N4     11
#define N5     12
#define N6     13
#define P4     14
#define N7     15
#define P6     16
#define B8     17
#define B9     18
#define N8     19
#define C3     20
#define N9     21
#define N10    22
#define N12    23
#define N13    24
#define P5     25
#define N14    26
#define S3     27
#define S4     28
#define N15    29
#define S5     30
#define C4     31
#define C5     32
#define B5     33
#define B6     34
#define B7     35
#define N16    36
#define N18    37
#define N19    38
#define P7     39
#define N20    40
#define N22    41
#define C6     42
#define C7     43
#define C8     44
#define C9     45
#define P8     46
#define N11    47
#define B10    48
#define B11    49

/* ===== 以下逐字来自 Navigation/map.c ===== */
#define TURN_D_CRIGHT   ( 11.0f)   /* 右斜线（右起2/3灯）—— 最晚触发，滞后最大 */
#define TURN_D_CLEFT    ( -4.0f)
#define TURN_D_DLEFT    ( -5.0f)
#define TURN_D_DEFAULT  ( -4.0f)
#define TURN_L_PIVOT    ( 19.0f)   /* 旋转中心→传感器板中心 纵向距离 */
#define TURN_GATE_CM    (  5.0f)

static const struct { u8 last, now, next; float dist; } kTurnTbl[] = {
	{ B9, N7, P6, 25 },
	{ P6, N7, B8, 20 },
	{ C4, N20, P8, 35 },
	{ N20, C4, B11, 25 },
	{ N3, N4, B2, 30 },
	{ P8, N20, C4, 30 },
	{ N8, N5, N4, 36 },
	{ N5, N8, N12, 20 },
	{ N8, N3, N4, 30 },
	{ N4, N3, N8, 20 },
	{ B8, N9, C3, 0 },
	{ N10, N9, B9, 48 },
	{ B2, N1, P1, 25 },
};

static float calc_src(u8 last, u8 now, u8 next, u8 IN_FUNC, u16 IN_STEP, float PHI, u8 arrive_method)
{
	u8    found = 0;
	float meas  = 19.0f;                 /* 默认值（原 return 19 的语义） */
	u8    i;

	meas  = ((last==B2 && now==N1 && next==P1) ? 25.0f : ((last==N10 && now==N9 && next==B9) ? 48.0f : ((last==B8 && now==N9 && next==C3) ? 0.0f : ((last==N4 && now==N3 && next==N8) ? 20.0f : ((last==N8 && now==N3 && next==N4) ? 30.0f : ((last==N5 && now==N8 && next==N12) ? 20.0f : ((last==N8 && now==N5 && next==N4) ? 36.0f : ((last==P8 && now==N20 && next==C4) ? 30.0f : ((last==N3 && now==N4 && next==B2) ? 30.0f : ((last==N20 && now==C4 && next==B11) ? 25.0f : ((last==C4 && now==N20 && next==P8) ? 35.0f : ((last==P6 && now==N7 && next==B8) ? 20.0f : ((last==B9 && now==N7 && next==P6) ? 25.0f : 0.0f)))))))))))));
	found = ((last==B2 && now==N1 && next==P1) ? 1 : ((last==N10 && now==N9 && next==B9) ? 1 : ((last==B8 && now==N9 && next==C3) ? 1 : ((last==N4 && now==N3 && next==N8) ? 1 : ((last==N8 && now==N3 && next==N4) ? 1 : ((last==N5 && now==N8 && next==N12) ? 1 : ((last==N8 && now==N5 && next==N4) ? 1 : ((last==P8 && now==N20 && next==C4) ? 1 : ((last==N3 && now==N4 && next==B2) ? 1 : ((last==N20 && now==C4 && next==B11) ? 1 : ((last==C4 && now==N20 && next==P8) ? 1 : ((last==P6 && now==N7 && next==B8) ? 1 : ((last==B9 && now==N7 && next==P6) ? 1 : 0)))))))))))));
	

#if TURN_CALC_ENABLE
	/* ---- Tier2：能算就算 ----
	 * ⚠️ 用启动时由边表建好的 Node[] 里的原始数据，不能读 nodes.nowNode.step/function：
	 *    door_set_pass_node() 会在跑的过程中把 step 改成 72/50/36、function 改成 NONE。 */
	{
		/* 入边属性由参数给出 */      /* "last→now" 这条入边的原始属性 */
		float phi = PHI;

		if ((IN_FUNC == NONE || IN_FUNC == DOOR) &&
			IN_STEP >= 20 &&
			phi >= 100.0f && phi < 178.0f)
		{
			float d = TURN_D_DEFAULT;
			if      (arrive_method == ARRIVE_CRIGHT) d = TURN_D_CRIGHT;
			else if (arrive_method == ARRIVE_CLEFT)  d = TURN_D_CLEFT;
			else if (arrive_method == ARRIVE_DLEFT)  d = TURN_D_DLEFT;
			/* cosf：M7 只有单精度 FPU，别用 double 的 cos */
			float calc = TURN_L_PIVOT * (1.0f - cosf(phi * (3.14159265f / 180.0f))) + d;

			/* 5cm 闸门：表里有实测值且公式与它差太多 → 放弃公式，用实测值 */
			if (!found || fabsf(calc - meas) <= TURN_GATE_CM)
				return calc;
		}
	}
#endif

	if (found)
		return meas;
	return 19;
}

/* ===== 逐例调用（编译检查类型/语法）===== */
volatile float probe_acc;
void probe_calls(void)
{
	float acc = 0.0f;
	acc += calc_src(31, 40, 46, 1, 170, 155.0f, 11);   /* T1 实测 | 期望 35.00 | 闸门挡回：公式47.2 vs 实测35 */
	acc += calc_src(11, 10, 19, 1, 108, 145.0f, 1);   /* T1 实测 | 期望 20.00 | 闸门挡回：公式29.6 vs 实测20 */
	acc += calc_src(19, 12, 11, 13, 100, 145.0f, 3);   /* T1 实测 | 期望 36.00 | 闸门挡回：公式30.6 vs 实测36 */
	acc += calc_src(22, 21, 18, 1, 156, 165.0f, 11);   /* T2 公式(过闸门) | 期望 48.35 | 过闸门：实测48 vs 公式48.4 */
	acc += calc_src(19, 10, 11, 13, 100, 145.0f, 3);   /* T2 公式(过闸门) | 期望 30.56 | 过闸门：实测30 vs 公式30.6 */
	acc += calc_src(10, 11, 4, 1, 130, 140.0f, 3);   /* T2 公式(过闸门) | 期望 29.55 | 过闸门：实测30 vs 公式29.6 */
	acc += calc_src(40, 31, 49, 1, 180, 125.0f, 3);   /* T2 公式(过闸门) | 期望 25.90 | 过闸门：实测25 vs 公式25.9 */
	acc += calc_src(12, 19, 23, 13, 100, 110.0f, 1);   /* T2 公式(过闸门) | 期望 20.50 | 过闸门：实测20 vs 公式20.5 */
	acc += calc_src(0, 10, 0, 1, 216, 175.0f, 1);   /* T2 公式(无实测) | 期望 32.93 | 无实测 → 公式 */
	acc += calc_src(4, 2, 4, 1, 40, 170.0f, 11);   /* T2 公式(无实测) | 期望 48.71 | 无实测 → 公式 */
	acc += calc_src(13, 12, 13, 1, 114, 100.0f, 1);   /* T2 公式(无实测) | 期望 17.30 | 无实测 → 公式 */
	acc += calc_src(31, 40, 31, 1, 170, 170.0f, 11);   /* T2 公式(无实测) | 期望 48.71 | 无实测 → 公式 */
	acc += calc_src(9, 10, 19, 1, 246, 35.0f, 2);   /* T3 默认19 | 期望 19.00 | T3 转弯<100 → 用实测6 */
	acc += calc_src(43, 44, 49, 1, 108, 180.0f, 0);   /* T3 默认19 | 期望 19.00 | T3 178°+无实测 → 默认19 */
	acc += calc_src(4, 11, 4, 1, 12, 180.0f, 0);   /* T3 默认19 | 期望 19.00 | T3 step<20+无实测 → 默认19 */
	acc += calc_src(5, 6, 7, 1, 40, 180.0f, 0);   /* T3 默认19 | 期望 19.00 | T3 障碍+无实测 → 默认19 */
	acc += calc_src(2, 1, 2, 1, 104, 180.0f, 0);   /* T3 默认19 | 期望 19.00 | T3 无实测+180° → 默认19 */
	acc += calc_src(17, 21, 20, 1, 1, 160.0f, 3);   /* T1 实测 | 期望 0.00 | T3 step=1 → 用实测0 */
	acc += calc_src(18, 15, 16, 1, 5, 170.0f, 1);   /* T1 实测 | 期望 25.00 | T3 step=5 → 用实测25 */
	probe_acc = acc;
}
